In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('dataset.csv')

In [3]:
#lets look at few rows
data.head()

Emotion  BAP1  BAP2  BAP3  BAP4  BAP5  BAP6  BAP7  BAP8  BAP9  ...  BAP259  \
0  NCIS/1  86.5  82.1  74.8   7.9  31.1  78.1  37.9  20.6  55.7  ...    38.4   
1  NCIS/2  18.5  88.2  24.3  14.4  13.1  40.4  69.7  73.3  48.7  ...    54.8   
2  NCIS/3  16.0  86.3  11.9  64.8  35.9  61.5  15.5  70.2  60.2  ...    18.9   
3  NCIS/4  63.5  64.7  29.1  34.1  24.5  84.2   7.1  49.3  14.1  ...    64.6   
4  NCIS/5  68.6  32.4  42.1  39.8  71.5  67.0  16.8  44.8  21.2  ...    73.8   

   BAP260  BAP261  BAP262  BAP263  BAP264  BAP265  BAP266  BAP267  BAP268  
0    57.9    21.1    64.2    23.4    29.4    76.7    32.8    81.9    11.5  
1    83.3    84.5    32.1    42.1    64.7    69.2    34.3    70.4    34.3  
2    75.2    93.7    49.6    36.0    31.5    22.3    15.9    78.8    13.2  
3    55.6    49.2    74.1    59.7    51.4    12.4    29.8    79.1    15.6  
4    39.4    36.7    71.5    61.4    45.3    67.5    33.7    76.2    24.8  

[5 rows x 269 columns]

In [4]:
#first we seperate label column Emotion
label=data.Emotion.values
data=data.drop(['Emotion'],axis=1)

In [5]:
data.head()

BAP1  BAP2  BAP3  BAP4  BAP5  BAP6  BAP7  BAP8  BAP9  BAP10  ...  BAP259  \
0  86.5  82.1  74.8   7.9  31.1  78.1  37.9  20.6  55.7   67.3  ...    38.4   
1  18.5  88.2  24.3  14.4  13.1  40.4  69.7  73.3  48.7   55.0  ...    54.8   
2  16.0  86.3  11.9  64.8  35.9  61.5  15.5  70.2  60.2   22.8  ...    18.9   
3  63.5  64.7  29.1  34.1  24.5  84.2   7.1  49.3  14.1   33.1  ...    64.6   
4  68.6  32.4  42.1  39.8  71.5  67.0  16.8  44.8  21.2   37.2  ...    73.8   

   BAP260  BAP261  BAP262  BAP263  BAP264  BAP265  BAP266  BAP267  BAP268  
0    57.9    21.1    64.2    23.4    29.4    76.7    32.8    81.9    11.5  
1    83.3    84.5    32.1    42.1    64.7    69.2    34.3    70.4    34.3  
2    75.2    93.7    49.6    36.0    31.5    22.3    15.9    78.8    13.2  
3    55.6    49.2    74.1    59.7    51.4    12.4    29.8    79.1    15.6  
4    39.4    36.7    71.5    61.4    45.3    67.5    33.7    76.2    24.8  

[5 rows x 268 columns]

In [6]:
#Lets enumerate labels 
mapping=dict()
for x,y in enumerate(label):
    mapping[x]=y
labels_enum=list(mapping.keys())

In [7]:
labels_enum[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
#Now we will filter only first 20 columns from dataset for data
value=data[['BAP1', 'BAP2', 'BAP3', 'BAP4', 'BAP5', 'BAP6', 'BAP7', 'BAP8', 'BAP9', 'BAP10', 'BAP11', 'BAP12', 'BAP13', 'BAP14', 'BAP15', 'BAP16', 'BAP17', 'BAP18', 'BAP19', 'BAP20']].values
value[:5]

array([[86.5, 82.1, 74.8,  7.9, 31.1, 78.1, 37.9, 20.6, 55.7, 67.3, 83.7,
        78.6, 15.1, 83. , 17.7, 43.1, 48. , 20.1, 23.4, 85.5],
       [18.5, 88.2, 24.3, 14.4, 13.1, 40.4, 69.7, 73.3, 48.7, 55. , 79. ,
        46.7, 70.9, 51. , 68.6, 47.5, 24.5, 64.6, 19.6, 74. ],
       [16. , 86.3, 11.9, 64.8, 35.9, 61.5, 15.5, 70.2, 60.2, 22.8, 55.1,
        68.6, 90.4, 62.2, 67. , 86.1, 66.1, 55.6, 30.5, 36.8],
       [63.5, 64.7, 29.1, 34.1, 24.5, 84.2,  7.1, 49.3, 14.1, 33.1, 70.3,
        88.1, 46.5, 79.4, 15.6, 55.4, 82.9, 63.7, 59.7, 63.1],
       [68.6, 32.4, 42.1, 39.8, 71.5, 67. , 16.8, 44.8, 21.2, 37.2, 32.8,
        83.9, 54.6, 80.8, 18.5, 60.2, 74.7, 29.7, 63.2, 70.4]])

In [11]:
import numpy as np
#Minimizing each value to 1
def preprocess(arr):
    new_arr=[]
    for each in arr:
        new_arr.append(each/100)
    new_arr=np.array(new_arr)
    return new_arr
process_val=preprocess(value)

In [12]:
process_val[:4]

array([[0.865, 0.821, 0.748, 0.079, 0.311, 0.781, 0.379, 0.206, 0.557,
        0.673, 0.837, 0.786, 0.151, 0.83 , 0.177, 0.431, 0.48 , 0.201,
        0.234, 0.855],
       [0.185, 0.882, 0.243, 0.144, 0.131, 0.404, 0.697, 0.733, 0.487,
        0.55 , 0.79 , 0.467, 0.709, 0.51 , 0.686, 0.475, 0.245, 0.646,
        0.196, 0.74 ],
       [0.16 , 0.863, 0.119, 0.648, 0.359, 0.615, 0.155, 0.702, 0.602,
        0.228, 0.551, 0.686, 0.904, 0.622, 0.67 , 0.861, 0.661, 0.556,
        0.305, 0.368],
       [0.635, 0.647, 0.291, 0.341, 0.245, 0.842, 0.071, 0.493, 0.141,
        0.331, 0.703, 0.881, 0.465, 0.794, 0.156, 0.554, 0.829, 0.637,
        0.597, 0.631]])

In [13]:
from sklearn.linear_model import LogisticRegression

In [17]:
model=LogisticRegression(multi_class='auto')
model.fit(process_val,labels_enum)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
import numpy as np
from random import randint
arr=[randint(1,100) for x in range(20)]
data_test=np.array([arr])
val_test=preprocess(data_test)
print(val_test)
prediction=model.predict(val_test)
prediction

[[0.49 0.18 0.55 0.73 0.39 0.12 0.94 0.7  0.82 0.77 0.3  0.16 0.22 0.86
  0.07 0.86 0.42 0.24 0.53 0.49]]


array([501])

In [30]:
from sklearn.externals import joblib

In [31]:
joblib_file = "joblib_model.pkl"
joblib.dump(model, joblib_file)

['joblib_model.pkl']